name: .NET release

on:
  release:
    types: [created]
   
jobs:
  build:
    uses: bluehands/WebFinger.Server.OidcDiscovery/.github/workflows/dotnet.yml@main
  publish:
    runs-on: ubuntu-latest
    needs: build
    env:
      wd: ./src/WebFinger.Server.OidcDiscovery
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x 
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.wd }}
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.wd }}
      - name: Create the package
        run: dotnet pack --configuration Release
        working-directory: ${{ env.wd }}
      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
